// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParabolicFunction.Models;

namespace ParabolicFunction.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200827203316_Storage")]
    partial class Storage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParabolicFunction.Models.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChartID");

                    b.Property<int>("PointX");

                    b.Property<int>("PointY");

                    b.Property<int?>("UserDataId");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("ParabolicFunction.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("A");

                    b.Property<int>("B");

                    b.Property<int>("C");

                    b.Property<int>("RangeFrom");

                    b.Property<int>("RangeTo");

                    b.Property<int>("Step");

                    b.HasKey("Id");

                    b.ToTable("UserDatas");
                });

            modelBuilder.Entity("ParabolicFunction.Models.Point", b =>
                {
                    b.HasOne("ParabolicFunction.Models.UserData", "UserData")
                        .WithMany()
                        .HasForeignKey("UserDataId");
                });
#pragma warning restore 612, 618
        }
    }
}
